# Site settings
title: Kyle Fiegener's Portfolio
email: KyleFiegener@gmail.com
author: Kyle Fiegener
description: Kyle Fiegener is a web developer who enjoys the merging of art and science that comes with full-stack development.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://psiradish.github.io" # the base hostname & protocol for your site
port: 9001
# twitter_username: himitsu!
github_username:  PsiRadish
linkedin: https://www.linkedin.com/in/KyleFiegener
collections:
  folio_items:
    output: true
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "folio_items"
    values:
      layout: "folio_item"

# Build settings
markdown: kramdown
destination: __site

# Sass settings
sass:
    style: expanded
